# Generated by Django 4.0.4 on 2022-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField(verbose_name='Prix (en Franc CFA)')),
                ('stock', models.FloatField(verbose_name='Stock')),
            ],
        ),
    ]
