# Generated by Django 4.0.4 on 2022-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAYMENT_EXPECTED', 'Paiement attendu'), ('PAID', 'Payé'), ('READY', 'Prêt'), ('TAKEN', 'Pris')], default='PAYMENT_EXPECTED', max_length=20)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('client', models.IntegerField()),
            ],
        ),
    ]
